### ISSUE TITLE
crashes on macOS - cannot write to disk

### ISSUE THREAD

**Issue by Kareldeij** [marcoatribeiro/FluentEmailer#2]
crashes on macOS saying that disk is read-only, this happens for both .send() and .SendAsync()

I am using .net 7.0, and visual studio for Mac to build

`Unhandled exception in circuit 'kDueDlkKPC0DiYIsFWNyGq_-k9Fu_EcmoN14DNtCnpM'.
      System.IO.IOException: Read-only file system : '/2023-08-23_12-05-40_244'
         at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
         at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Func4 createOpenException)
         at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func4 createOpenException)
         at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable 1 unixCreateMode)
         at System.IO.File.OpenWrite(String path)
         at FluentEmailer.Core.Defaults.SaveToDiskSender.SaveEmailToDisk(IFluentEmailer emailer) in /_/Src/FluentEmailer.Core/Defaults/SaveToDiskSender.cs:line 29
         at FluentEmailer.Core.Defaults.SaveToDiskSender.SendAsync(IFluentEmailer emailer, CancellationToken token) in /_/Src/FluentEmailer.Core/Defaults/SaveToDiskSender.cs:line 20
         at FluentEmailer.Core.Defaults.SaveToDiskSender.Send(IFluentEmailer emailer, CancellationToken token) in /_/Src/FluentEmailer.Core/Defaults/SaveToDiskSender.cs:line 14
         at FluentEmailer.Core.Email.Send(CancellationToken token) in /_/Src/FluentEmailer.Core/Email.cs:line 326
         at Ea.SendMail() in /Users/../.../.kl.net/src/...POS/Pages/Pos/Pos.razor:line 48
         at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[T](MulticastDelegate delegate, T arg)
         at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.DispatchEventAsync(UInt64 eventHandlerId, EventFieldInfo fieldInfo, EventArgs eventArgs)
`

**Comment by marcoatribeiro** [comment]
I've built the solution on Rider for Mac and ran the unit tests. Everything looks fine. A few questions:

1. Any special reason for you to use `SaveToDiskSender`? Have you tried with any of the other senders (Smtp, for instance)?
2. Have you tried using the original [FluentEmail](https://github.com/lukencode/FluentEmail) lib? Does this issue occur there as well?

**Comment by marcoatribeiro** [comment]
Closed due to lack of response
